name: Run Automated Checks

on:
  push:
    branches:
      - '**'

    tags-ignore:
      - v*

jobs:
  # pre-commit checks
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
      name: Run Pre Commit Checks

  # black formatter
  black-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: Ahuge/black-action@master
        name: Run Black Formatter Checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLACK_ARGS: "."

  # pypi build test
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Package Build
        env:
          STACKMANAGER_VERSION: 9999
        run: |
          python setup.py sdist bdist_wheel
